Upgrade to the latest go version
Conflux-Chain/confura pull request #179
Opened 2024-03-22 08:53 UTC by wanliqun

2024-03-22 09:01 UTC, wanliqun commented
@boqiu 
Hold until `https://github.com/Conflux-Chain/go-conflux-util/pull/26` has been approved and integrated

2024-03-22 11:08 UTC, boqiu requested changes
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Conflux-Chain/confura/179)* status: all files reviewed, 1 unresolved discussion (waiting on @wanliqun)

___
*[`go.mod` line 7 at r1](https://reviewable.io/reviews/Conflux-Chain/confura/179#-Nt_qCYw-22-qE2Cu46i:-Nt_qCYw-22-qE2Cu46j:bhcxl6t) ([raw file](https://github.com/Conflux-Chain/confura/blob/f9ef039e872f72d8677ca8a8ce26e2acb525d784/go.mod#L7)):*
> ```XML
> require (
> 	github.com/Conflux-Chain/go-conflux-sdk v1.5.9
> 	github.com/Conflux-Chain/go-conflux-util v0.1.1-0.20231220063312-4844964b9b11
> ```

version not changed?


<!-- Sent from Reviewable.io -->

2024-03-25 06:41 UTC, wanliqun reviewed
> *[Reviewable](https://reviewable.io/reviews/Conflux-Chain/confura/179)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @boqiu)

___
*[`go.mod` line 7 at r1](https://reviewable.io/reviews/Conflux-Chain/confura/179#-Nt_qCYw-22-qE2Cu46i:-NtoKfRK9LvfT9HcPILy:b8qwnlv) ([raw file](https://github.com/Conflux-Chain/confura/blob/f9ef039e872f72d8677ca8a8ce26e2acb525d784/go.mod#L7)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

version not changed?
</blockquote></details>

`go-conflux-util` version upgraded to v0.2.0


<!-- Sent from Reviewable.io -->

2024-03-27 12:36 UTC, boqiu approved these changes

2024-03-28 02:05 UTC, merged